Routing/2s2e/changes to routing
TritonSE/CBL-Mobile-Application pull request #49
Opened 2023-06-01 05:11 UTC by 2s2e

### Tracking Info

Resolves #46 

### Changes
-Fixed a bunch of bugs to do with header widgets not having the proper parameters
-Profile button on bottom bar, when signed out, takes user to the sign in page
-Back button on have your voice heard goes to the previous screen so that it works both when signed in and signed out
-Resources, when signed in, goes to have your voice heard

### Testing

How did you confirm your changes worked? 

Features were tested both signed in and signed out:
When signed out,
-clicking on the profile button redirects to the sign in page

When signed in,
-clicking on resources brings user to have your voice heard
-back button on have your voice goes back to home page

### Confirmation of Change 

When signed out:
-Click on the profile button to confirm it goes to sign in

When signed in:
-First sign in by creating an account
-After signing in, click on resources, which should redirect to have_your_voice_heard
-Click the back button to confirm the app redirects back to the home page

2023-10-19 05:38 UTC, petabite requested changes
nice!

2023-10-19 05:38 UTC, petabite commented on lib/pages/call_text_now.dart
> +        resourcesRoute: '/haveYourVoiceHeard',
should this be the coming soon page?
```suggestion
        resourcesRoute: '/comingSoonResources',
```

2023-10-20 04:23 UTC, petabite approved these changes
👌🏼

2023-11-01 23:43 UTC, aaronchan32 approved these changes
Looks good to me!

2023-11-02 00:16 UTC, merged